- name: Ensure Grafana data dir exists
  ansible.builtin.file:
    path: "{{ grafana_data_path }}"
    state: directory
    mode: '0755'
  become: true

- name: Copy Grafana datasource
  ansible.builtin.copy:
    src: datasource.yml
    dest: "{{ grafana_data_path }}/datasource.yml"
    mode: '0644'
  become: true

- name: Run Grafana container
  community.docker.docker_container:
    name: "{{ grafana_container_name }}"
    image: "{{ grafana_image }}"
    restart_policy: "{{ grafana_restart_policy }}"
    env:
      GF_SECURITY_ADMIN_USER: "{{ grafana_admin_user }}"
      GF_SECURITY_ADMIN_PASSWORD: "{{ grafana_admin_password }}"
      GF_USERS_ALLOW_SIGN_UP: "{{ grafana_users_allow_sign_up }}"
    ports:
      - "{{ grafana_ports }}"
    volumes:
      - "{{ grafana_data_path }}/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml"
    networks:
      - name: "{{ docker_network }}"

- name: Confirm Grafana is live
  ansible.builtin.debug:
    msg: "Grafana → http://{{ hostvars[inventory_hostname].ansible_host }}:{{ grafana_port }}"
  changed_when: false
